### ISSUE TITLE
Issue running basic commands

### ISSUE THREAD

**Issue by jjg8282** [m-laniakea/st_spin#1]
Hi! When running the basic commands you have listed in the readme I have run into an issue I can't seem to figure out. When I compile and run the code I receive an error when calling the move function. The error states: TypeError: unsupported operand types(s) for |: 'int' and 'SpinValue'. 

I'm fairly new to python so I'm sorry if it's a dumb error!

**Comment by m-laniakea** [comment]
This was certainly my mistake, not yours.
Hopefully you were able to find another solution.
