### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by digitalfotografen** [m-laniakea/st_spin#6]
Please add License to this repo. My suggestion is to use MIT-licence (a common choice for this type of projects).
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

This is a great implementation of the base functions needed to use the L6470 stepper driver (and related). Great job!
I would like to continue the development by implementing higher level commands, and submit this back to Your repo. But to do this I need to know that it is released with a compatible open source license. I have use for this library in work for a client (to use in their research lab).

**Comment by m-laniakea** [comment]
Hi Mr. Södergren, thank you for the nice comment.

MIT license added.

If you still have use for this library, please be aware that I no longer have the resources to further develop this library.
Submitting merge requests here would work, or you may want to create a fork.

Wishing you much success in your projects!

**Comment by digitalfotografen** [comment]
Thanks for adding MIT licens!
I'll start using this an continue development later this Year. I'll make a fork to offload the work of handling pull-requests.

Thanks for creating this lib, it really helped my getting started with this typ of stepper driver.
