### ISSUE TITLE
Conection between Raspberry 4b and RoboFun L6470 board

### ISSUE THREAD

**Issue by adrianlupoian** [m-laniakea/st_spin#7]
Can you tell me how to connect GPIO with this board?
https://www.aliexpress.com/item/1564532401.html
Thank you.

**Comment by m-laniakea** [comment]
https://blog.stabel.family/raspberry-pi-4-multiple-spis-and-the-device-tree/
^ This should help you.

Here's a pinout diagram: https://pinout.xyz/pinout/spi

```
(PI4) (Board)
5V    5V
GND   GND
MOSI  SDI
MISO  SDO
SCLK  CK
CE0   CSN?
```
Probably! Verify for yourself, because it's been a long time.
Keep in mind that the motor requires its own power connection.

**Comment by adrianlupoian** [comment]
Thank you very much. Now I use an S board nucleo ihm 02A1 board with 2
l6470.
I use your library. The problem is that all registers are 0x00 at getStatus
command. Have an ideea?
Adrian

**Comment by m-laniakea** [comment]
If all your data is 0, the MISO pin is likely not receiving any data.

02A1 are the boards I used in the past. Double-check that your SPI bridges are correct.
